-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.18-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table laravelecom_db.airport_city
CREATE TABLE IF NOT EXISTS `airport_city` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `icao_code` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `iata_code` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `airport_name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `City` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `province` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=152 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Dumping data for table laravelecom_db.airport_city: ~151 rows (approximately)
DELETE FROM `airport_city`;
/*!40000 ALTER TABLE `airport_city` DISABLE KEYS */;
INSERT INTO `airport_city` (`id`, `icao_code`, `iata_code`, `airport_name`, `City`, `province`, `created_at`, `updated_at`) VALUES
	(1, 'WIAS', 'MLG', 'Abdul Rachman Saleh', 'Malang, Jawa Timur', '', NULL, NULL),
	(2, 'WIAS', 'MLG', 'Abdul Rachman Saleh', 'Malang, Jawa Timur', '', NULL, NULL),
	(3, 'WASC', 'RSK', 'Abresso', 'Ransiki, Manokwari', 'Papua', NULL, NULL),
	(4, 'WIIS', 'SRG', 'Achmad Yani', 'Semarang', 'Jawa Tengah', NULL, NULL),
	(5, 'WARJ', 'JOG', 'Adi Sutjipto', 'Yogyakarta', 'DI Yogyakarta', NULL, NULL),
	(6, 'WRSQ', 'SOC', 'Adi Sumarmo', 'Solo', 'Jawa Tengah', NULL, NULL),
	(7, 'WIME', 'AEG', 'Aek Godang', 'Padang Sidempuan', 'Sumatera Utara', NULL, NULL),
	(8, 'WATM', 'ARD', 'Pulau Alor', 'Pulau Alor', 'Nusa Tenggara Timur', NULL, NULL),
	(9, 'WAPA', 'AHI', 'Amahai', 'Amahai', 'Papua', NULL, NULL),
	(10, 'WAAM', 'MXB', 'Andi Jemma', 'Masamba', 'Sulawesi Selatan', NULL, NULL),
	(11, '', 'AGD', 'Anggi', 'Anggi, Manokwari', 'Papua', NULL, NULL),
	(12, '', 'AAS', 'Apalapsili', 'Apalapsili, Yalimo', 'Papua', NULL, NULL),
	(13, 'WAJA', 'ARJ', 'Arso', 'Arso, Keerom', 'Papua', NULL, NULL),
	(14, '', 'AYW', 'Ayawasi', 'Ayawasi, Maybrat', 'Papua', NULL, NULL),
	(15, 'WASO', 'BXB', 'Babo', 'Babo, Teluk Bintuni', 'Papua', NULL, NULL),
	(16, 'WAKE', 'BXD', 'Bade', 'Bade, Merauke', 'Papua', NULL, NULL),
	(17, '', 'BXM', 'Batom', 'Batom, Jayawijaya', 'Papua', NULL, NULL),
	(18, 'WRBC', 'BTW', 'Batulicin', 'Batulicin, Kalimantan Selatan', '', NULL, NULL),
	(19, 'WALK', 'BEJ', 'Berau (Kalimaru)', 'Tanjung Redeb, Berau', 'Kalimantan Timur', NULL, NULL),
	(20, 'WAAB', 'BUW', 'Betoambari', 'Bau Bau, Pulau Buton', 'Sulawesi Tenggara', NULL, NULL),
	(21, 'WIMB', 'GNS', 'Binaka', 'Gunungsitoli', 'Sumatera Utara', NULL, NULL),
	(22, 'WAJB', 'BUI', 'Bokondini', 'Bokondini, Tolikara', 'Papua', NULL, NULL),
	(23, '', 'BJG', 'Bolaang', 'Bolaang Mogondow', 'Sulawesi Utara', NULL, NULL),
	(24, 'WRLC', 'BXT', 'Bontang', 'Bontang', 'Kalimantan Timur', NULL, NULL),
	(25, 'WAMW', 'LUW', 'Bubung', 'Luwuk', 'Sulawesi Tengah', NULL, NULL),
	(26, 'WIKD', 'TJQ', 'Bulutumbang', 'Tanjung Pandan', 'Kepulauan Bangka Belitung', NULL, NULL),
	(27, 'WRLV', 'BYQ', 'Bunyu', 'Pulau Bunyu', 'Kalimantan Timur', NULL, NULL),
	(28, 'WIAM', 'TSY', 'Cibeureum', 'Tasikmalaya', 'Jawa Barat', NULL, NULL),
	(29, 'WIIC', 'CBN', 'Cirebon', 'Cirebon', 'Jawa Barat', NULL, NULL),
	(30, 'WITC', 'MEQ', 'Cut Nyak Dien', 'Meulaboh', 'Aceh', NULL, NULL),
	(31, 'WIKS', 'SIQ', 'Dabo', 'Singkep', 'Riau', NULL, NULL),
	(32, 'WAPD', 'DOB', 'Dobo', 'Dobo, Kepulauan Aru', 'Maluku', NULL, NULL),
	(33, 'WAPL', 'LUV', 'Dumatubin', 'Langgur, Tual', 'Maluku Tenggara', NULL, NULL),
	(34, 'WRKK', 'KOE', 'El Tari', 'Kupang', 'Nusa Tenggara Timur', NULL, NULL),
	(35, 'WABT', 'EWI', 'Enarotali', 'Enarotali, Paniai', 'Papua', NULL, NULL),
	(36, 'WABB', 'BIK', 'Frans Kaisiepo', 'Biak', 'Papua', NULL, NULL),
	(37, 'WAMA', 'GLX', 'Gamarmalamo', 'Galela', 'Halmahera Utara', NULL, NULL),
	(38, 'WRKL', 'LKA', 'Gewayentana', 'Larantuka', 'Flores Timur', NULL, NULL),
	(39, 'WIAG', 'AKQ', 'Gunung Batin', 'Astraksetra, Tulang Bawang', 'Lampung', NULL, NULL),
	(40, 'WIHH', 'HLP', 'Halim Perdanakusuma', 'Jakarta', '', NULL, NULL),
	(41, 'WRKA', 'ABU', 'Haliwen', 'Atambua', 'Nusa Tenggara Timur', NULL, NULL),
	(42, 'WIDD', 'BTH', 'Hang Nadim', 'Batam', 'Riau', NULL, NULL),
	(43, 'WRBS', 'SMQ', 'Haji Asan', 'Sampit', 'Kalimantan Tengah', NULL, NULL),
	(44, 'WAAA', 'UPG', 'Hasanuddin', 'Makassar', 'Sulawesi Selatan', NULL, NULL),
	(45, 'WICC', 'BDO', 'Husein Sastranegara', 'Bandung', 'Jawa Barat', NULL, NULL),
	(46, 'WABL', 'ILA', 'Ilaga', 'Ilaga', 'Papua', NULL, NULL),
	(47, 'WASI', 'INX', 'Inanwatan', 'Inanwatan, Sorong Selatan', 'Papua', NULL, NULL),
	(48, 'WRKE', 'ENE', 'Ipi', 'Ende', 'Nusa Tenggara Timur', NULL, NULL),
	(49, 'WRBI', 'PKN', 'Iskandar Muda', 'Pangkalan Bun', 'Aceh', NULL, NULL),
	(50, 'WIIX', 'JKT', 'Jakarta (city)', 'Jakarta', '', NULL, NULL),
	(51, 'WIPR', 'RGT', 'Japura', 'Rengat', 'Riau', NULL, NULL),
	(52, 'WASS', 'SOQ', 'Jefman', 'Sorong', 'Papua', NULL, NULL),
	(53, 'WABF', 'FOO', 'Jembruwo', 'Numfor, Biak', 'Papua', NULL, NULL),
	(54, 'WRSJ', 'SUB', 'Juanda', 'Surabaya', 'Jawa Timur', NULL, NULL),
	(55, 'WRLB', 'LBW', 'Juvai Semaring', 'Long Bawan', 'Kalimantan Timur', NULL, NULL),
	(56, 'WRLR', 'TRK', 'Juwata', 'Tarakan', 'Kalimantan Timur', NULL, NULL),
	(57, 'WASK', 'KNG', 'Kaimana', 'Kaimana', 'Papua', NULL, NULL),
	(58, 'WAMP', 'PSJ', 'Kasiguncu', 'Poso', 'Sulawesi Tengah', NULL, NULL),
	(59, 'WASE', 'KEQ', 'Kebar', 'Kebar, Manokwari', 'Papua', NULL, NULL),
	(60, 'WIPV', 'KLQ', 'Keluang', 'Keluang', 'Sumatera Selatan', NULL, NULL),
	(61, 'WAKP', 'KEI', 'Kepi', 'Kepi, Merauke', 'Papua', NULL, NULL),
	(62, 'WIKN', 'TNJ', 'Kijang', 'Tanjung Pinang', 'Kepulauan Riau', NULL, NULL),
	(63, 'WRKO', 'LBJ', 'Komodo', 'Labuhan Bajo', 'Flores', NULL, NULL),
	(64, 'WAMI', 'TLI', 'Lalos', 'Toli Toli', 'Sulawesi Tengah', NULL, NULL),
	(65, 'WAJL', 'LHI', 'Lereh', 'Lereh, Jayapura', 'Papua', NULL, NULL),
	(66, 'WITL', 'LSX', 'Lhok Sukon', 'Lhok Sukon (Lhoksukon)', 'Aceh', NULL, NULL),
	(67, 'WRLP', 'LPU', 'Long Apung', 'Long Apung, Malinau', 'Kalimantan Timur', NULL, NULL),
	(68, 'WIAA', 'SBG', 'Maimun Saleh', 'Sabang', 'Aceh', NULL, NULL),
	(69, 'WAPE', 'MAL', 'Mangole', 'Mangole', 'Maluku Utara', NULL, NULL),
	(70, 'WAMN', 'MNA', 'Melangguane', 'Melangguane, Talaut', 'Sulawesi Utara', NULL, NULL),
	(71, 'WASM', 'RDE', 'Merdei', 'Merdei, Teluk Bintuni', 'Papua', NULL, NULL),
	(72, 'WIPT', 'PDG', 'Minangkabau', 'Ketaping / Padang', 'Sumatera Barat', NULL, NULL),
	(73, 'WAKD', 'MDP', 'Mindiptana', 'Mindiptana, Boven Digoel', 'Papua', NULL, NULL),
	(74, 'WABD', 'ONI', 'Moanamani', 'Moanamani, Dogiyal', 'Papua', NULL, NULL),
	(75, 'WAKK', 'MKQ', 'Mopah', 'Merauke', 'Papua', NULL, NULL),
	(76, 'WRRB', 'BMU', 'Muhammad Salahuddin', 'Bima, Sumbawa', 'Nusa Tenggara Barat', NULL, NULL),
	(77, 'WIPU', 'MPC', 'Muko Muko', 'Bengkulu', '', NULL, NULL),
	(78, 'WAJM', 'LII', 'Mulia', 'Mulia', 'Papua', NULL, NULL),
	(79, 'WAML', 'PLW', 'Mutiara', 'Palu', 'Sulawesi Tengah', NULL, NULL),
	(80, 'WABI', 'NBX', 'Nabire', 'Nabire', 'Papua', NULL, NULL),
	(81, 'WAMH', 'NAH', 'Naha', 'Naha, Sangihe', 'Sulawesi Utara', NULL, NULL),
	(82, 'WAPR', 'NAM', 'Namlea', 'Namlea, Buru', 'Maluku', NULL, NULL),
	(83, 'WIOG', 'NPO', 'Nangapinoh', 'Melawi', 'Kalimantan Barat', NULL, NULL),
	(84, 'WAPK', 'BJK', 'Nangasuri', 'Benjina', 'Maluku Tenggara', NULL, NULL),
	(85, 'WRSC', 'CPF', 'Ngloram', 'Cepu', 'Jawa Tengah', NULL, NULL),
	(86, 'WADD', 'DPS', 'Ngurah Rai', 'Denpasar', 'Bali', NULL, NULL),
	(87, 'WRLF', 'NNX', 'Nunukan', 'Nunukan', 'Kalimantan Timur', NULL, NULL),
	(88, 'WAKO', 'OKQ', 'Okaba', 'Okaba, Merauke', 'Papua', NULL, NULL),
	(89, 'WAJO', 'OKL', 'Oksibil', 'Oksibil', 'Pegunungan Bintang Papua', NULL, NULL),
	(90, 'WIPA', 'DJB', 'Paalmerah', 'Jambi', '', NULL, NULL),
	(91, 'WIPL', 'BKS', 'Padangkemiling (Fatmawati Soekarno)', 'Bengkulu', '', NULL, NULL),
	(92, 'WRKB', 'BJW', 'Padhameleda', 'Bajawa', 'Nusa Tenggara Timur', NULL, NULL),
	(93, 'WIKK', 'PGK', 'Pangkalpinang', 'Pangkal Pinang', 'Bangka-Belitung', NULL, NULL),
	(94, 'WIOP', 'PSU', 'Pangsuma', 'Putusibau', 'Kalimantan Barat', NULL, NULL),
	(95, 'WAPP', 'AMQ', 'Pattimura', 'Ambon', 'Maluku', NULL, NULL),
	(96, 'WIPQ', 'PDO', 'Pendopo', 'Pendopo', 'Sumatera Selatan', NULL, NULL),
	(97, 'WIBD', 'DUM', 'Pinang Kampai', 'Dumai', 'Riau', NULL, NULL),
	(98, 'WAMR', 'OTI', 'Pitu', 'Morotai', 'Maluku', NULL, NULL),
	(99, 'WIMM', 'MES', 'Polonia', 'Medan', 'Sumatera Utara', NULL, NULL),
	(100, 'WIIP', 'PCB', 'Pondok Cabe', 'Jakarta', '', NULL, NULL),
	(101, 'WQKN', '', 'Primapun', 'Primapun', '', NULL, NULL),
	(102, 'WIAT', 'TKG', 'Radin Inten II (Branti)', 'Bandar Lampung', 'Lampung', NULL, NULL),
	(103, 'WIOK', 'KTG', 'Rahadi Usman', 'Ketapang', 'Kalimantan Barat', NULL, NULL),
	(104, 'WION', 'NTX', 'Ranai', 'Natuna', 'Kepulauan Riau', NULL, NULL),
	(105, 'WASR', 'MKW', 'Rendani', 'Manokwari', 'Papua', NULL, NULL),
	(106, 'WIBR', 'RKO', 'Rokot', 'Sipora', 'Sumatera Barat', NULL, NULL),
	(107, 'WAMM', 'MDC', 'Sam Ratulangi', 'Manado', 'Sulawesi Utara', NULL, NULL),
	(108, 'WAPN', 'SQN', 'Sanana', 'Sanana', 'Maluku Utara', NULL, NULL),
	(109, '', 'SAE', 'Sangir', 'Sangir', 'Sulawesi Utara', NULL, NULL),
	(110, 'WRLT', 'TSX', 'Santan', 'Tanjung Santan', 'Kalimantan Timur', NULL, NULL),
	(111, 'WRKG', 'RTG', 'Satartacik', 'Ruteng', 'Nusa Tenggara Timur', NULL, NULL),
	(112, 'WAPI', 'SXK', 'Saumlaki', 'Saumlaki', 'Maluku', NULL, NULL),
	(113, 'WRRA', 'AMI', 'Selaparang', 'Mataram', 'Nusa Tenggara Barat', NULL, NULL),
	(114, 'WAJS', 'SEH', 'Senggeh', 'Senggeh', 'Papua', NULL, NULL),
	(115, 'WAJJ', 'DJJ', 'Sentani', 'Jayapura', 'Papua', NULL, NULL),
	(116, 'WALL', 'BPN', 'Sepinggan', 'Balikpapan', 'Kalimantan Timur', NULL, NULL),
	(117, 'WRBK', 'KBU', 'Setagen', 'Kotabaru', 'Kalimantan Selatan', NULL, NULL),
	(118, 'WIKL', 'LLG', 'Silampari', 'Lubuk Linggau, Musi Rawas', 'Sumatera Selatan', NULL, NULL),
	(119, 'WIMN', 'SQT', 'Silangit', 'Siborong-borong', 'Sumatera Utara', NULL, NULL),
	(120, 'WIII', 'CGK', 'Soekarno-Hatta', 'Cengkareng', 'Banten', NULL, NULL),
	(121, 'WAAS', 'SQR', 'Soroako', 'Soroako', 'Sulawesi Selatan', NULL, NULL),
	(122, 'WAMT', 'TTE', 'Sultan Babullah', 'Ternate', 'Maluku', NULL, NULL),
	(123, 'WITT', 'BTJ', 'Sultan Iskandarmuda (Blang Bintang)', 'Banda Aceh', 'Aceh', NULL, NULL),
	(124, 'WIPP', 'PLM', 'Sultan Mahmud Badaruddin II', 'Palembang', 'Sumatera Selatan', NULL, NULL),
	(125, 'WIBB', 'PKU', 'Sultan Syarif Kasim II (Simpang Tiga)', 'Pekanbaru', 'Riau', NULL, NULL),
	(126, 'WRRS', 'SWQ', 'Sumbawa Besar', 'Sumbawa', 'Nusa Tenggara Barat', NULL, NULL),
	(127, 'WIBT', 'TJB', 'Sunjai Bati', 'Tanjung Balai', 'Sumatera Utara', NULL, NULL),
	(128, 'WIOO', 'PNK', 'Supadio', 'Pontianak', 'Kalimantan Barat', NULL, NULL),
	(129, 'WIOS', 'SQG', 'Susilo', 'Sintang', 'Kalimantan Barat', NULL, NULL),
	(130, 'WRBB', 'BDJ', 'Syamsudin Noor', 'Banjarmasin', 'Kalimantan Selatan', NULL, NULL),
	(131, 'WAPT', 'TAX', 'Taliabu', 'Taliabu', 'Maluku Utara', NULL, NULL),
	(132, 'WRRT', 'TMC', 'Tambolaka', 'Waikabubak', 'Nusa Tenggara Timur', NULL, NULL),
	(133, 'WAAJ', 'MJU', 'Tampa Padang', 'Mamuju', 'Sulawesi Barat', NULL, NULL),
	(134, 'WRLH', 'TNB', 'Tanah Grogot', 'Tanah Grogot', 'Kalimantan Timur', NULL, NULL),
	(135, 'WAKT', 'TMH', 'Tanah Merah', 'Tanah Merah, Boven Digoel', 'Papua', NULL, NULL),
	(136, 'WAST', 'TXM', 'Teminabuan', 'Teminabuan, Sorong', 'Papua', NULL, NULL),
	(137, 'WRLS', 'SRI', 'Temindung', 'Samarinda', 'Kalimantan Timur', NULL, NULL),
	(138, 'WITA', 'TPK', 'Teuku Cut Ali', 'Tapak Tuan', 'Aceh', NULL, NULL),
	(139, 'WABP', 'TIM', 'Timika', 'Tembagapura', 'Papua', NULL, NULL),
	(140, 'WRBP', 'PKY', 'Tjilik Riwut (Panarung)', 'Palangkaraya', 'Kalimantan Tengah', NULL, NULL),
	(141, 'WASF', 'FKQ', 'Torea', 'Fak Fak', 'Papua', NULL, NULL),
	(142, 'WRST', 'SUP', 'Trunojoyo', 'Sumenep', 'Madura', NULL, NULL),
	(143, 'WIHL', 'CXP', 'Tunggul Wulung', 'Cilacap', 'Jawa Tengah', NULL, NULL),
	(144, 'WABG', 'WET', 'Wagethe', 'Wagethe', 'Papua', NULL, NULL),
	(145, 'WRKC', 'MOF', 'Wai Oti', 'Maumere', 'Nusa Tenggara Timur', NULL, NULL),
	(146, 'WRRW', 'WGP', 'Waingapu', 'Waingapu', 'Nusa Tenggara Timur', NULL, NULL),
	(147, 'WAJW', 'WMX', 'Wamena', 'Wamena', 'Papua', NULL, NULL),
	(148, 'WAJR', 'WAR', 'Waris', 'Waris', 'Papua', NULL, NULL),
	(149, 'WRBN', 'TJS', 'Warukin', 'Tanjung Selor', 'Kalimantan Timur', NULL, NULL),
	(150, 'WASW', 'WSR', 'Wasior', 'Wasior, Teluk Wondama', 'Papua', NULL, NULL),
	(151, 'WAAU', 'KDI', 'Wolter Monginsidi', 'Kendari', 'Sulawesi Tenggara', NULL, NULL);
/*!40000 ALTER TABLE `airport_city` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
